kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-nexus
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # CHANGE ME  
    path: "/VOLUMES/nexus"
